DEFAULT_MODE = "test"
DEFAULT_MODEL_NAME = "clock_tracking.h5"
DEFAULT_IMAGES_COUNT = 30000
DEFAULT_BATCH_SIZE = 32
DEFAULT_NUMBER_OF_EPOCHS = 10
DEFAULT_VALIDATION_SPLIT = 0.2
DEFAULT_NOISE_THRESHOLD = 0.6

IMAGE_WIDTH = 100
IMAGE_HEIGHT = 100
IMAGE_CHANNELS = 1

OUTPUT_SPACE_DIMENSIONALITY = IMAGE_WIDTH + IMAGE_HEIGHT

AVAILABLE_CLOCK_TYPES = ["B", "C", "D", "F", "G", "H", "I", "J", "K", "L", "M", "N"]