DEFAULT_MODE = "test"
DEFAULT_MODEL_NAME = "time_reading.h5"

DEFAULT_IMAGES_COUNT = 30000
DEFAULT_BATCH_SIZE = 32
DEFAULT_NUMBER_OF_EPOCHS = 20
DEFAULT_VALIDATION_SPLIT = 0.2
DEFAULT_NOISE_THRESHOLD = 0.3

IMAGE_WIDTH = 100
IMAGE_HEIGHT = 100
IMAGE_CHANNELS = 1

AVAILABLE_CLOCK_TYPES = ["B", "C", "D", "F", "G", "H", "I", "J", "K", "L", "M", "N"]